id: P4668FEC0
initial_creation_type: ocr
source_metadata:
  volumes:
    8fb5d3bc59bd4e79b69317818b23af65:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: རྣལ་འབྱོར་གསུམ་པ་ལ་འཇུག་པ།
      total_pages: 1902
      volume_number: 64
